driver:
  name: vagrant
 
platforms:
  - name: bento/centos-7
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8

provisioner:
  salt_version: latest
  name: salt_solo
  formula: supervisor
  require_chef: false
  pillars-from-files:
    supervisor.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
           - supervisor

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - supervisor

verifier:
  name: shell
  command: testinfra -vvv --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE

